bundler_args: --without development
language: ruby
rvm:
  - 2.2.0
# TODO: Change this to use addons.apt once sphinxsearch is whitelisted
before_install:
  - sudo apt-get update
  - sudo apt-get install -y sphinxsearch
before_script:
  - mysql -e 'create database elmo_test;'
  - "for f in $(find -name '*.example'); do cp \"$f\" \"${f%.example}\"; done"
  - "sed -ri 's/user: elmo/user: travis/; /password:/d' config/database.yml"
  - bundle exec rake ts:conf ts:start db:setup
script: bundle exec rake
env:
  global:
