---
bundler_args: --without development
language: ruby
cache: bundler
rvm:
  - 2.2.0
sudo: false
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - for f in $(find -name '*.example'); do cp "$f" "${f%.example}"; done
  - cp config/database.yml.travis config/database.yml
  # Remove recaptcha settings in local config so they are picked up from ENV. This is brittle
  # and should go away when we get rid of local_config.rb some sweet day.
  - sed -ri '/(public|private)_key = nil/d' config/initializers/local_config.rb
  - bundle exec rake db:setup
script: bundle exec rake
env:
  global:
    # Set reCAPTCHA keys to dummy values
    - RECAPTCHA_PUBLIC_KEY=6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
    - RECAPTCHA_PRIVATE_KEY=6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx
addons:
  artifacts:
    paths:
    - $(ls /home/travis/build/thecartercenter/elmo/tmp/capybara/*.png | tr "\n" ":")
  postgresql: "9.4"

notifications:
  slack:
    secure: N2dcQMxN6oZbCLgmB/fHhqv/+Su9FzAo3ULYbSd0lFz7PQgtUuEB6Hn13eSV7CIiAMPSM1Bfe0AFUJmSKOKYylF2k3kKuSL6jijnuK4AA4b9kNoPHt0wYEO+uAFO27pyvV+Uq21Gov8SWDVvRbQ3799c3Dl3/D3H6UhEAv7vgYY=
